# Generated by Django 5.0.6 on 2024-05-13 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("djangomapapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Marker",
        ),
    ]
